In [1]:
import pandas as pd
import numpy as np
import ast

### annotation of problems_with_features.csv:

* __Name:__ _*(from MoonBoard database, scraped data)_ name of the route 

* __Grade:__ _*(from MoonBoard database, scraped data)_ difficulty grade of the route in Fontainebelau System

    Annotaion: Two bouldering grading system are avaible in MoonBoard app: Hueco(USA, V-scale) and Fontainebleau(French). 
Fontainebleau system is more precise than Hueco, i.e. there are more grade classes in Fontainebleau system. [Comparison Chart](https://99boulders.com/wp-content/uploads/2014/11/Bouldering-Grades-e1505766945353.jpg) 

* __Moves:__ _*(from MoonBoard database, scraped data)_ Holds in a route. List of dictionaries. Dictionaries include holds' information in a route: 
    * Descripton -name of the hold(string), 
    * IsStart(boolean), 
    * IsEnd(boolean).
    * Id: NOTE: Id information is not consistent. ID's of the same hold in different problems are different.

* __Id:__ _(from MoonBoard database, scraped data)_ Id of the route.

### columns created in feature_extractor_draft1 jupyter notebook:


* __number_of_holds:__ number of holds in the problem


* __holds:__ list of holds in the route


* __lengths_of_moves:__ Lenghts of all possible moves in a route. Euclidean distances between all binary combinations of holds in the problem

In [2]:
# problems
problems = pd.read_csv("problems_with_features.csv")
problems.drop(["Unnamed: 0"], axis=1, inplace=True)


# converts cells' types from str to original type(list, dict, etc.)

 # Moves column
problem_list = []
for problem in problems["Moves"].values:
    problem_as_lst = ast.literal_eval(problem)
    problem_list.append(problem_as_lst)
problems["Moves"] = problem_list

 # Holdsets column
problem_list = []
for problem in problems["Holdsets"].values:
    problem_as_lst = ast.literal_eval(problem)
    problem_list.append(problem_as_lst)
problems["Holdsets"] = problem_list

 # lengths_of_moves column
problem_list = []
for problem in problems["lengths_of_moves"].values:
    problem_as_lst = ast.literal_eval(problem)
    problem_list.append(problem_as_lst)
problems["lengths_of_moves"] = problem_list

 # Holds column
problem_list = []
for problem in problems["holds"].values:
    problem_as_lst = ast.literal_eval(problem)
    problem_list.append(problem_as_lst)
problems["holds"] = problem_list

In [3]:
problems

,Name,Grade,Moves,Holdsets,Id,holds,number_of_holds,lengths_of_moves
0,BLACK BEAUTY,8B,"[{'Id': 1542554, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",82224,"[J5, I9, E14, H18]",4,"{'J5toJ5': 0.0, 'J5toI9': 4.123105625617661, '..."
1,PROJECT 2,8A+,"[{'Id': 1535606, 'Description': 'K6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",62575,"[K6, K7, D10, H14, A16, A18]",6,"{'K6toK6': 0.0, 'K6toK7': 1.0, 'K6toD10': 8.06..."
2,SHATTERED MERCY,8A+,"[{'Id': 1596473, 'Description': 'D3', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",241045,"[D3, B4, G7, I8, K12, H14, H15, C18]",8,"{'D3toD3': 0.0, 'D3toB4': 2.23606797749979, 'D..."
3,ATTIC ADDICT,8A,"[{'Id': 1986894, 'Description': 'E6', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",350783,"[E6, G2, J6, F8, J12, F15, F16, A18]",8,"{'E6toE6': 0.0, 'E6toG2': 4.47213595499958, 'E..."
4,BUNNY,8A,"[{'Id': 1521147, 'Description': 'B4', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",23184,"[B4, G7, H7, K8, K10, K13, G16, H18]",8,"{'B4toB4': 0.0, 'B4toG7': 5.830951894845301, '..."
...,...,...,...,...,...,...,...,...
446,JUST ANOTHER DAY,6C,"[{'Id': 1555486, 'Description': 'F5', 'IsStart...","[{'Id': 0, 'Description': 'Original School Hol...",125131,"[F5, J5, J8, K11, I12, I14, E15, E18]",8,"{'F5toF5': 0.0, 'F5toJ5': 4.0, 'F5toJ8': 5.0, ..."
447,LE UOVA SODE,6C,"[{'Id': 1680083, 'Description': 'E13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",274947,"[E13, F5, G18, I10, I12, I14, J8]",7,"{'E13toE13': 0.0, 'E13toF5': 8.06225774829855,..."
448,LOW CARB VAR,6C,"[{'Id': 1527581, 'Description': 'K5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set A', 'Color...",39242,"[K5, G8, D9, H11, E13, B16, E18]",7,"{'K5toK5': 0.0, 'K5toG8': 5.0, 'K5toD9': 8.062..."
449,MAFFEI,6C,"[{'Id': 1523127, 'Description': 'J5', 'IsStart...","[{'Id': 0, 'Description': 'Hold Set B', 'Color...",27102,"[J5, E12, A14, E8, D18]",5,"{'J5toJ5': 0.0, 'J5toE12': 8.602325267042627, ..."
450,MOON CASTLE,6C,"[{'Id': 1844732, 'Description': 'B13', 'IsStar...","[{'Id': 0, 'Description': 'Original School Hol...",196769,"[B13, D18, D10, E12, E16, G9, I5, K5]",8,"{'B13toB13': 0.0, 'B13toD18': 5.38516480713450..."

### annotation of holds_with_features.csv:

_whole csv.file is created in feature_extractor_draft1 jupyter notebook. Not scraped from MoonBoard database. Based on problems.csv and my analysis of physical MoonBoard 2016 layout_ 


* __name:__ Name of the hold

* __grade_Distribution:__ difficulty grade distribution of the hold in Fontainebelau System

* __color:__ The color of the hold - string

* __black:__ Binary - 0 or 1

* __white:__ Binary - 0 or 1

* __yellow:__ Binary - 0 or 1

* __force_z:__
    * ordinal: 0, 1 or 2. 
    * direction of force at z: 
    * Can one grip the hold and apply force at Z direction (outwards, perpendicular to the wall)
    * it indirectly gives an idea of a hold's incut size(larger incut size, easier to grip, so easier route) 

* __rotational angle:__ Rotational angle of the hold
    * (categorical) 
    What I mean by rotational angle of a hold is that in which direction one can apply force to a hold. For example, one can only apply force to hold A5 downwards, whereas you can apply force to hold E14 both leftwards and rightwards. I believe it will be useful information when we set conditions to decide transition through states
    * (*Mert will analyze moonboard and fill the column)

* __slopeness:__ (ordinal or binary) - Is hold slope in its rotational angle. Sloper holds are harder to grab. 
    * (*Mert will analyze moonboard and fill the column)

In [4]:
# holds
holds = pd.read_csv("holds_with_features.csv")
holds.drop(["Unnamed: 0"], axis=1, inplace=True)

# converts cells' types from str to original type(list, dict, etc.)

 # grade_distribution column
grade_distributions_lst = []
for gradeDistribution in holds["grade_distribution"].values:
    problem_as_dict = ast.literal_eval(gradeDistribution)
    grade_distributions_lst.append(problem_as_dict)
holds["grade_distribution"] = grade_distributions_lst


holds

,name,grade_distribution,color,black,white,yellow,force_z,rotational_angle,slopeness
0,A5,"{'6B+': 5, '6C': 4, '6C+': 7, '7A': 9, '7A+': ...",white,0,1,0,0,NaN,NaN
1,A9,"{'6B+': 2, '6C': 4, '6C+': 1, '7A': 2, '7A+': ...",black,1,0,0,1,NaN,NaN
2,A10,"{'6B+': 0, '6C': 0, '6C+': 0, '7A': 0, '7A+': ...",yellow,0,0,1,0,NaN,NaN
3,A11,"{'6B+': 0, '6C': 0, '6C+': 0, '7A': 0, '7A+': ...",yellow,0,0,1,0,NaN,NaN
4,A12,"{'6B+': 0, '6C': 0, '6C+': 1, '7A': 1, '7A+': ...",white,0,1,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
135,K12,"{'6B+': 1, '6C': 1, '6C+': 0, '7A': 0, '7A+': ...",yellow,0,0,1,0,NaN,NaN
136,K13,"{'6B+': 0, '6C': 0, '6C+': 0, '7A': 0, '7A+': ...",yellow,0,0,1,0,NaN,NaN
137,K14,"{'6B+': 0, '6C': 1, '6C+': 2, '7A': 0, '7A+': ...",black,1,0,0,2,NaN,NaN
138,K16,"{'6B+': 1, '6C': 1, '6C+': 0, '7A': 0, '7A+': ...",black,1,0,0,1,NaN,NaN
139,K18,"{'6B+': 5, '6C': 5, '6C+': 4, '7A': 4, '7A+': ...",white,0,1,0,2,NaN,NaN